services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'

  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    command: >
      sh -c "npx wait-port db:5432 && npm run db:migrate && npx prisma db seed && npm run start"


